title: Hdemica - bibliographies
author: 
  name: Arianna Masciolini
  email: arianna.masciolini@gu.se
description: > 
  Arianna Masciolini's academic reading.

remote_theme: jekyll/minima

header_pages:
  - nonexisting_page

minima:
  skin: dark
  date_format: "%-d %B %Y"
  social_links:
    - { platform: github, user_url: https://github.com/harisont }
    - { platform: stackoverflow, user_url: https://stackoverflow.com/users/7729724/harisont }
    - { platform: instagram, user_url: https://www.instagram.com/unottica/ }
    - { platform: youtube, user_url: https://www.youtube.com/c/ImparalHaskellemettilodaparte }
    - { platform: rss, user_url: https://harisont.github.io/feed.xml}